### ISSUE TITLE
Install command is wrong?

### ISSUE THREAD

**Issue by jd615645** [duskmoon314/vue3-typed-js#51]
in this repo readme (not works)
![image](https://user-images.githubusercontent.com/9366364/220399850-fb4bcf5c-9d1e-46d1-856a-db4392716c6a.png)
![image](https://user-images.githubusercontent.com/9366364/220400159-7931ff1d-68b6-40f4-8db7-bd26c4730c76.png)

in npm page (works)
![image](https://user-images.githubusercontent.com/9366364/220399877-f1427330-7c9d-450f-b293-3c28f15b2f0c.png)

**Comment by duskmoon314** [comment]
Oh, that's a mistake. My fault.
