### ISSUE TITLE
[plugin:vite:import-analysis] Failed to resolve entry for package "@duskmoon/vue3-typed-js"

### ISSUE THREAD

**Issue by pratyushtewari** [duskmoon314/vue3-typed-js#55]
Hi @duskmoon314  - I am getting the following error in my nuxt3 (vue3) project.

I am using the same example that you provided in the readme file for this project.
```
[plugin:vite:import-analysis] Failed to resolve entry for package "@duskmoon/vue3-typed-js". The package may have incorrect main/module/exports specified in its package.json.
```

Let me know if you know what could be the issue? 

P.S. I am very new to vite.

Also, the [npm readme](https://www.npmjs.com/package/@duskmoon/vue3-typed-js) says to install the other package so that is also confusing me.
<img width="219" alt="image" src="https://user-images.githubusercontent.com/251768/228579998-37afa748-e647-46ee-beee-199d4f5d3796.png">

**Comment by duskmoon314** [comment]
> Also, the [npm readme](https://www.npmjs.com/package/@duskmoon/vue3-typed-js) says to install the other package so that is also confusing me.

I'm not very familiar with npm, and I wonder why npm is not using the latest README. 😢 

I reproduce this problem. I will see what's wrong and reply as soon as possible.

**Comment by pratyushtewari** [comment]
Thank you! Cant wait!

**Comment by duskmoon314** [comment]
It seems the problem is caused by the build artifact named `vue3-typed-js.mjs` instead of `vue3-typed-js.es.js`. I will fix the `package.json` and release a new version.

**Comment by pratyushtewari** [comment]
I see you updated the package. 

```
yarn install v1.22.19
[1/4] Resolving packages...
Couldn't find any versions for "@duskmoon/vue3-typed-js" that matches "^0.0.4"
? Please choose a version of "@duskmoon/vue3-typed-js" from this list: (Use arrow keys)
> 0.0.3
  0.0.2
  0.0.1
```

The npmjs is not updated yet. I'll give it some more time and check out later.

**Comment by pratyushtewari** [comment]
However, I checked using a local yarn link and the latest commit is working great. Thank you!

**Comment by duskmoon314** [comment]
> The npmjs is not updated yet. I'll give it some more time and check out later.

I used GitHub action to publish the package, and it turned out to be down. So I will publish it by hand soon.

**Comment by duskmoon314** [comment]
0.0.4 has been published. I hope everything goes fine.

**Comment by pratyushtewari** [comment]
It works! thank you so much for the quick fix.
