### ISSUE TITLE
Copying simple demo, and got an error

### ISSUE THREAD

**Issue by QyInvoLing** [duskmoon314/vue3-typed-js#58]
I simply entered these vue template elements  provided in the demo of this project, and the browser console give out an error.
Deleting the class declaration of both the <Typed> tag and the span tag will solve this. As a result, I can't even pick the inner element of <Typed> tag in CSS.
```
<Typed :options="typedOptions">
      <span class="typer_span" ></span>
    </Typed>
```

Error detail:
```
vue3-typed-js.mjs:364  Uncaught TypeError: Cannot read properties of null (reading 'tagName')
    at i.value (vue3-typed-js.mjs:364:139)
    at new o (vue3-typed-js.mjs:70:41)
    at vue3-typed-js.mjs:672:20
    at runtime-core.esm-bundler.js:2675:88
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2655:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:325:40)
    at render2 (runtime-core.esm-bundler.js:6335:5)
    at mount (runtime-core.esm-bundler.js:3824:13)
```

**Comment by QyInvoLing** [comment]
Sorry I got this mistake by vue-router, not this project.

**Comment by duskmoon314** [comment]
I think this problem corresponds with the implementation. I use the same method as `vue-typed-js`, which needs the inner part to use the `typing` class.

https://github.com/duskmoon314/vue3-typed-js/blob/ecb7de869c07f6f5f4a672e8688ba93b4912deb4/src/components/Typed.tsx#L21

I haven't tried with other classes.

**Comment by QyInvoLing** [comment]
> I think this problem corresponds with the implementation. I use the same method as `vue-typed-js`, which needs the inner part to use the `typing` class.
> 
> https://github.com/duskmoon314/vue3-typed-js/blob/ecb7de869c07f6f5f4a672e8688ba93b4912deb4/src/components/Typed.tsx#L21
> 
> I haven't tried with other classes.

Yes, you're right. I found that actually it's not caused by vue router, but my wrong spelling in css class name(I use _, not -, which is not so normative). After I saw the querySelector you posted, I finally realized that it's all my fault. Thanks!
